### PR TITLE
Fix article order

### LINKED ISSUE #8: Messes up the ordering of `articles`
Microposts seem to mess up the ordering of the ``articles`` list passed to the templating engine. Use ``dates`` instead (which is sorted by date)?

### PR DESCRIPTION
**Pull request by ashwinvis**
- **Add type annotations to generator**
- **Insert microblog article by date, assume rev. chrono. order**

Fixes #8

### CODE REVIEW

**Comment by ashwinvis** [comment]
This is the default ordering, but one could support more by inspecting the value of `ARTICLE_ORDER_BY`

https://docs.getpelican.com/en/4.9.1/settings.html

**Comment by MinchinWeb** [comment]
Thanks for this! It's taking me a little longer to review this, but I'll get to it. Respecting `ARTICLE_ORDER_BY` would be ideal... (but not a show stopper)

**Comment by ashwinvis** [comment]
@MinchinWeb I added some basic support for `ARTICLE_ORDER_BY`

**Comment by MinchinWeb** [comment]
Thanks for tackling this, but it doesn't seem to sort for me as expected :( 

image

(This is the test site that's part of this repo, using the modified *seafoam* theme at https://github.com/MinchinWeb/seafoam/tree/microblog ).

I also started trying to see if I could reuse the existing sorting code withing *Pelican*, but it fails the same way; see https://github.com/MinchinWeb/minchin.pelican.readers.microblog/tree/sorting

Do I need to go something particular to get this working?

**Comment by ashwinvis** [comment]
Your test site contains no microblog files.

https://github.com/MinchinWeb/seafoam/tree/microblog/test/content

I added some from mine into the theme and added the plugin and it works well

```diff
diff --git a/test/pelicanconf.py b/test/pelicanconf.py
index aca2af7..b276dda 100644
--- a/test/pelicanconf.py
+++ b/test/pelicanconf.py
@@ -10,6 +10,8 @@ try:
 except ImportError:
     fancy_tasklist = None

+from minchin.pelican.readers import microblog
+
 # THEME = seafoam.get_path()
 # BOOTSTRAP_THEME = "seafoam"
 PATH = "content"
@@ -23,6 +25,7 @@ PLUGINS = [
     "pelican.plugins.seafoam",
     # "pelican.plugins.jinja_filters",
     # "pelican.plugins.image_process",
+    microblog,
 ]
 if commonmark:
     PLUGINS = PLUGINS + [
```

image

**Comment by MinchinWeb** [comment]
> Your test site contains no microblog files.

I'm actually using the test site with this plugin, rather than the seafoam one.
https://github.com/MinchinWeb/minchin.pelican.readers.microblog/tree/master/test

But it looks like it's working! Turns out the microposts on July 8th in my sample site are from this year, and the July 13th post is from last year!

I'm not at my regular computer, but I'll push a release with this when I return. Thanks for your patience with me. And thanks for contributing this too!

**Comment by MinchinWeb** [comment]
@ashwinvis v1.3.0 has been releases with this included! Please let me know if you run into any issues.

**Pull request merged**
