### PR TITLE
Modified metadata handling from pelicanconf and microblog post, adds 2 new config variables 

### PR DESCRIPTION
**Pull request by ashwinvis**
- **Allow for Python 3.9**
- **Add MICROBLOG_CATEGORY configuration variable**
- **Allow overriding configured microblog metadata from a post**
- **Ensure default author if not mentioned in micro blog**
- **Comment out unused imports**
- **Add MICROBLOG_APPEND_HASHTAGS configuration variable**

### CODE REVIEW

**Comment by ashwinvis** [comment]
@MinchinWeb sorry for not opening an issue to discuss these changes, but I made a few changes for my blog, and I believe it is good to have it merged upstream. Let me know if you need any clarification.

**Comment by MinchinWeb** [comment]
Hi ashwinvis! Thank you for this! It's always delightful to find out my code is helpful to someone else. I'll push an update to PyPI with this shortly.

**Comment by ashwinvis** [comment]
You are welcome and thank you for the plugin!

**Comment by MinchinWeb** [comment]
v1.2.0 is [now out](https://pypi.org/project/minchin.pelican.readers.microblog/1.2.0/)!

Turns out Pelican is perfectly happy if you don't set an author for a post (so I added some code to not brake in that case) and I added some test posts.

Please test it out, and let me know if you run into any issues.

Also, if you have any more improvements, feel free to send them may way; they are always appreciated.

**Pull request merged**
